services:
  - type: web
    name: cookthelefts
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: SPOONACULAR_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cookthelefts_db
          property: connectionString

databases:
  - name: cookthelefts_db
    databaseName: cookthelefts
    ipAllowList: []
