services:
  - type: web
    name: cookthelefts
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn "app:create_app('production')" --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cookthelefts_db
          property: connectionString

databases:
  - name: cookthelefts_db
    databaseName: cookthelefts
    ipAllowList: []
