"""add video link to recipes

Revision ID: 008042066bfe
Revises: 95148f344d4d
Create Date: 2025-01-30 12:19:44.411275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '008042066bfe'
down_revision = '95148f344d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_link', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('video_link')

    # ### end Alembic commands ###
